#define MYRAILIO_VERSION						"0.0.01"
#define MYRAILIO_STATUS						"DEV" //"STABLE", "BETA", "ALPHA", "DEV"
#define MYRAILIO_GITHUB_COMMIT_ID			
#define MYRAILIO_BUILD_DATE					
#define MYRAILIO_BUILD_ID					

